fixes
fixes to build docs

diff --git a/.github/workflows/build_test_notebooks.yml b/.github/workflows/build_test_notebooks.yml
--- a/.github/workflows/build_test_notebooks.yml
+++ b/.github/workflows/build_test_notebooks.yml
@@ -19,27 +19,41 @@ jobs:
         with:
           repository: StingraySoftware/stingray
           path: ./stingray
-          submodules: true
+          submodules: recursive
 
-      - name: Checkout PR version of notebooks
-        if: github.event_name == 'pull_request'
+      - name: Get latest commit of the PR
+        id: pr_commit
         run: |
-          cd ./stingray/notebooks  # Change to the submodule directory
-          git fetch origin pull/${{ github.event.pull_request.number }}/head:PR_${{ github.event.pull_request.number }}
-          git checkout PR_${{ github.event.pull_request.number }}
+          PR_SHA=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r .head.sha)
+          if [ "$PR_SHA" == "null" ]; then
+            echo "::error::Failed to get PR SHA"
+            exit 1
+          fi
+          echo "::set-output name=commit::$PR_SHA"
+      - name: Checkout PR version of notebooks
+        run: |
+          cd ./stingray/docs/notebooks # Change to the submodule directory
+          pwd
+          git fetch origin ${{ steps.pr_commit.outputs.commit }}:pr_temp
+          git checkout pr_temp
+      - name: Verify submodule update
+        run: |
+          cd ./stingray/docs/notebooks
+          git log -1
       - name: Setup Python
         uses: actions/setup-python@v5
         with:
           python-version: '3.10'
 
-      - name: Install pandoc and dependencies
+      - name: Install pandoc and additional dependencies
         run: |
           sudo apt-get update
           sudo apt-get install -y pandoc fonts-freefont-ttf
           pip install sphinx sphinx-astropy tox
+          
       - name: Install Stingray
-        run: pip install -e ./stingray
-
+        run: |
+          pip install -e ./stingray
       - name: Run Build Docs
         run: |
           cd ./stingray
