from_stingray

diff --git a/.github/workflows/build_docs.yml b/.github/workflows/build_docs.yml
--- a/.github/workflows/build_docs.yml
+++ b/.github/workflows/build_docs.yml
@@ -16,32 +16,43 @@ jobs:
         with:
           repository: StingraySoftware/stingray
           path: ./stingray
+
       - name: Checkout notebooks repo
         uses: actions/checkout@v4
         with:
-          repository: AnonymousCodes911/notebooks  
-          ref: tox_update  
+          repository: AnonymousCodes911/notebooks
+          ref: tox_update
           path: ./notebooks
+
       - name: Setup Python
         uses: actions/setup-python@v5
         with:
           python-version: '3.10'
+
       - name: Install pandoc and dependencies
         run: |
           sudo apt-get update
           sudo apt-get install -y pandoc fonts-freefont-ttf
           pip install sphinx sphinx-astropy nbsphinx tox 
+
       - name: Install Stingray
-        run: pip install -e git+https://github.com/StingraySoftware/stingray.git#egg=stingray
+        run: |
+          cd ./stingray
+          pip install -e .
+
       - name: Update submodules
         run: |
+          cd ./notebooks
           git submodule update --init --recursive
-        working-directory: ./notebooks
-      - name: Checkout notebooks submodule branch
+
+      - name: Check current directory
         run: |
-          git checkout tox_update
-        working-directory: ./notebooks
+          if [[ "$(pwd)" != "${GITHUB_WORKSPACE}/stingray" ]]; then
+            echo "Error: not in the stingray main directory"
+            exit 1
+          fi
 
       - name: Run Build Docs
-        run: tox -e build_docs
-        working-directory: ./notebooks
+        run: |
+          cd ./notebooks
+          tox -e build_docs
